server.port=8080
spring.application.name=client_register

#Base de datos
spring.datasource.url=jdbc:mysql://root:heeBwxvIPnurjjnXwqkffhKntGzbmWnW@nozomi.proxy.rlwy.net:49064/railway
spring.datasource.username=root
spring.datasource.password=heeBwxvIPnurjjnXwqkffhKntGzbmWnW
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#RabbitMQ
spring.rabbitmq.addresses=amqps://pwphtwrk:gB1eWNEOVIoG8cD6f7aq0zLBGGo2AX39@jackal.rmq.cloudamqp.com/pwphtwrk
spring.rabbitmq.ssl.enabled=true
